### ISSUE TITLE
Hide private travelnets

### ISSUE THREAD

**Issue by thomasrudin** [minetest-tools/mapserver#44]
Pandorabox convention: "(P) name"

@SwissalpS Would that solve (one) of your problems?

**Comment by SwissalpS** [comment]
no, because they can still be searched in the online map and the
coordinates show up. They then just need to take jumpdrive there.
But I'm OK with travelnets being visible as we can use mission blocks. But
for them to be usefull, their 'hidden' setting needs to be respected by
mapserver.

/* * * Luke@SwissalpS.ws * * */

**Comment by thomasrudin** [comment]
Uhm, no: they are not searchable that way, thats the whole point :)

**Comment by SwissalpS** [comment]
try it. search for (P) you will get a ton of results and after clicking 'go
to' you can see the travelnet icon, click on that and you have the
coordinates.
/* * * Luke@SwissalpS.ws * * */

**Comment by SwissalpS** [comment]
I have used it as a feature to find jump drives that went rogue or bugged
out the travelnet.
/* * * Luke@SwissalpS.ws * * */

**Comment by thomasrudin** [comment]
> try it. search for (P) you will get a ton of results and after clicking 'go
to' you can see the travelnet icon, click on that and you have the
coordinates.

That was not yet implemented, this is an `issue`, means a bug or a feature-request.
