### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by thomasrudin** [minetest-tools/mapserver#46]
```
find . -name '*.go' | xargs -I % sed -i -e 's,mapserver/,github.com/thomasrudin-mt/mapserver/,g' %
```

**Comment by thomasrudin** [comment]
go11module issue (@tuedel)
```
env GO111MODULE=on go build
```

**Comment by tuedel** [comment]
cc @ma27, who fixed the build for nixpks

**Comment by thomasrudin** [comment]
@Ma27 I have the feeling there are a few bugs i don't know about :confused: 
Feel free to use the issue tracker or contact me on Freenode IRC (BuckarooBanzai)

@tuedel i'm reworking the frontend on the master branch, its not really stable just fyi :smile:

**Comment by Ma27** [comment]
I'll probably be able to take a look at this tomorrow :)

**Comment by Ma27** [comment]
@tuedel I updated the gist I originally hacked together for this package: https://gist.github.com/Ma27/2fc15c1aac766af510bef2922525e368/revisions#diff-5712e736e0de6ba170577f8472c398e9

The package could be simplified by using [buildGoModule](https://kalbas.it/2019/03/17/announcing-the-new-golang-infrastructure-buildgomodule/) which automates a lot of building stuff and appears to be rather robust (I tend to use this for a lot of Go-stuff where I encounter building issues :sweat_smile: )

Please note that the package is *not* part of nixpkgs, fpletz asked me build the package a while ago which is why this gist exists, I assume that one of you folks added this to your nixpkgs fork :)
I could push this to nixpkgs-upstream, but in that case I'd prefer to wait for v4 (I just used the latest revision for testing purposes) and it would be cool to have a co-maintainer for the package :)
